package com.Semafoor.ToDoList.Model;

import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import javax.persistence.*;

/*
The Boodschap class is annotated as @Entity to declare we want objects of class Boodschap to be persistant.
It extends AbstractEntity so it inherits al variables declared there. It is also registered to the
AuditingEntityListener, see the AbstractEntity class for more info.

The @Id, @GeneratedValue and @SequenceGenerator annotations are all from javas own persistance libraries.
@Id marks the id instance variable as the primary key of this class. The @GeneratedValue annotation means that
the value of id, will be generated by the database. Additional information on how we want the Id values of boodscahp
to be sequenced is provided by the @SequenceGenerator annotation.
 */

@Entity
@EntityListeners(AuditingEntityListener.class)
public class Boodschap extends AbstractEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "boodschapSequence")
    @SequenceGenerator(name = "boodschapSequence", initialValue = 100, sequenceName = "boodschap_seq")
    private long id;

    private String title;

    private boolean completed;

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public boolean isCompleted() {
        return completed;
    }

    public void setCompleted(boolean completed) {
        this.completed = completed;
    }
}
